### ISSUE TITLE
How to query? (basic)

### ISSUE THREAD

**Issue by rkoberg** [ruslantalpa/postgrest-rls-example#1]
(should I ask this on the postgrest issues queue?)
I am not sure I understand how this is supposed to work. Also not sure if I am doing things correctly to achieve the result I am looking for. After looking at the tests, I set up a query like below. My understanding is that I should not be able to see user_id=1's (admin) projects. Is that the case? But I do.

```
set local role employee;
--set postgrest.claims.company_id = '1';
set postgrest.claims.user_id = '3';

select * from api.users_projects where user_id=3 or user_id=1
```

Results in:

```
"user_id","project_id"
1,1
3,1
```

**Comment by ruslantalpa** [comment]
no, that is not the case.
as an employee you should see the info about the projects you participate in, that means also other users that participate in that project (i am not saying this is the correct approach, it's just how i thought it should work in this example, i might have missed some "business rules").
the condition is here https://github.com/ruslantalpa/postgrest-rls-example/blob/master/sql/api_schema.sql#L97

also, uncomment the company_id claim, that is also used.
